project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"

website:
  title: "Mana Sakai"
  # page-footer: Footer
  search: false
  navbar:
    title: "Mana Sakai"
    tools:
      - icon: twitter-x
        text: X
        href: https://x.com/_iammana
      - icon: github
        text: GitHub
        href: https://github.com/manasakai
    left:
      - text: "Home"
        href: /index.html
      - text: "Research"
        href: /pages/research.html

format:
  html:
    css: ./styles/theme_default.css
    toc: false
    title-block-banner: ./images/banner.jpeg
